# Generated by Django 6.0.3 on 2026-03-29 23:07
from django.conf.global_settings import AUTH_USER_MODEL
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_deadline_issue_issue_severity_and_more'),
    ]

    operations = [
        migrations.RunSQL('INSERT INTO auth_user VALUES (1, 1234, \'2026-3-19 10:23:54+02\', True, \'admin\', \'admin\', \'admin\', \'admin@system.com\', True, True, \'2025-3-19 10:23:54+02\' )')
    ]
